apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceService
metadata:
  name: redhataiqwen25-7b-instruct
  namespace: dybbol
  annotations:
    opendatahub.io/connections: secret-6a153e
    opendatahub.io/genai-use-case: coi
    opendatahub.io/hardware-profile-name: gpu-profile
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/model-type: generative
    openshift.io/description: qwen 2.5
    openshift.io/display-name: RedHatAI/Qwen2.5-7B-Instruct
    security.opendatahub.io/enable-auth: "false"
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/genai-asset: "true"
spec:
  model:
    name: redhataiqwen25-7b-instruct
    uri: oci://registry.redhat.io/rhelai1/modelcar-qwen2-5-7b-instruct:1.5
  replicas: 2
  router:
    gateway: {}
    route: {}
    scheduler: {}
  template:
    containers:
    - name: main
      resources:
        limits:
          cpu: "1"
          memory: 12Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 12Gi
          nvidia.com/gpu: "1"
