apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: authorino
  namespace: redhat-ods-applications
spec:
  clusterWide: true
  replicas: 1
  logLevel: info
  listener:
    tls:
      enabled: false
  oidcServer:
    tls:
      enabled: false
