apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: rhoai-model-registries
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "registry"
  MYSQL_DATABASE: "registry"
  MYSQL_USER: "registry"
  MYSQL_PASSWORD: "registry"