apiVersion: v1
kind: Service
metadata:
  name: maas-postgresql
  namespace: redhat-ods-applications
  labels:
    app: maas-postgresql
spec:
  selector:
    app: maas-postgresql
  ports:
  - port: 5432
    targetPort: 5432
