# This patch manifest enables the LlamaStack Operator in the Data Science Cluster (DSC).
# LlamaStack Operator is a component of RHOAI that provides support for running Llama models in the cluster.
# apply this patch using the following command: 
# oc patch DataScienceCluster default-dsc \
#   --type=merge \
#   --patch-file manifests/05/rhoai-dsc-enable-llamastack.yaml
spec:
  components:
    llamastackoperator:
      managementState: Managed
